# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

Layout/FirstMethodArgumentLineBreak:
  Enabled: true

Layout/FirstArgumentIndentation:
  Enabled: true
  EnforcedStyle: consistent
  IndentationWidth: 2

Layout/MultilineMethodArgumentLineBreaks:
  Enabled: true

Layout/ArgumentAlignment:
  Enabled: true
  EnforcedStyle: with_fixed_indentation
  IndentationWidth: 2

# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false
